name: Incorrect Information
description: Report incorrect pass or resort information on the website.
labels: 'template: incorrect information'
assignees:
  - epic-vs-ikon-support
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report.

        **Please note:** This report will be publicly visible.
  - type: dropdown
    id: category
    attributes:
      label: What type of information is incorrect?
      options:
        - Pass price
        - Pass perk
        - Resort information
        - Resort access level
        - Map data
        - Linked information
        - Other
    validations:
      required: true
  - type: input
    id: entity
    attributes:
      label: Where is the incorrect information?
      description: Which pass or resort has incorrect information?
      placeholder: ex. Ikon Base Pass price, Breckenridge skiable acres, etc.
    validations:
      required: true
  - type: input
    id: incorrect-info
    attributes:
      label: Incorrect information
      description: What value is incorrect?
      placeholder: ex. 290 acres
    validations:
      required: false
  - type: input
    id: correct-info
    attributes:
      label: Correct information
      description: What should the value be?
      placeholder: ex. 2,908 acres
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Any additional information?
      description: Please provide any additional information that may be helpful.
      placeholder: My source for this information is...
    validations:
      required: false
