name: Feature Request
description: Tell us what you'd like to see on the website.
labels: 'template: feature request'
assignees:
  - epic-vs-ikon-support
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature.
        
        **Please note:** This report will be publicly visible.
  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: Short list of what the feature request aims to address?
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Why do you think this feature is needed?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: How should this feature be implemented?
    validations:
      required: true
